---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "cronjob-etcd-backup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cronjob-etcd-backup.labels" . | nindent 4 }}