---
kind: Template
apiVersion: v1
metadata:
  name: cronjob-prune-images
  annotations:
    description: Scheduled Task to Prune Images from Internal Docker Registry
    iconClass: icon-shadowman
    tags: management,cronjob,prune,images
objects:
- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: "${JOB_NAME}"
  spec:
    schedule: "${SCHEDULE}"
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: "${{SUCCESS_JOBS_HISTORY_LIMIT}}"
    failedJobsHistoryLimit: "${{FAILED_JOBS_HISTORY_LIMIT}}"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: "${JOB_NAME}"
              image: "${IMAGE}:${IMAGE_TAG}"
              command:
              - "/bin/bash"
              - "-c"
              - oc adm prune images --keep-tag-revisions=$IMAGE_PRUNE_KEEP_TAG_REVISIONS
                --keep-younger-than=$IMAGE_PRUNE_KEEP_YOUNGER_THAN --confirm
              env:
              - name: IMAGE_PRUNE_KEEP_TAG_REVISIONS
                value: "${IMAGE_PRUNE_KEEP_TAG_REVISIONS}"
              - name: IMAGE_PRUNE_KEEP_YOUNGER_THAN
                value: "${IMAGE_PRUNE_KEEP_YOUNGER_THAN}"
            restartPolicy: Never
            terminationGracePeriodSeconds: 30
            activeDeadlineSeconds: 500
            dnsPolicy: ClusterFirst
            serviceAccountName: "${JOB_SERVICE_ACCOUNT}"
            serviceAccount: "${JOB_SERVICE_ACCOUNT}"
    startingDeadlineSeconds: ${{STARTING_DEADLINE_SECONDS}}
- kind: ClusterRoleBinding
  apiVersion: v1
  metadata:
    name: system:image-pruners
    labels:
      template: "cronjob-prune-images"
  roleRef:
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    name: ${JOB_SERVICE_ACCOUNT}
  userNames:
  - system:serviceaccount:${NAMESPACE}:${JOB_SERVICE_ACCOUNT}
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: ${JOB_SERVICE_ACCOUNT}
    labels:
      template: "cronjob-prune-images"
parameters:
- name: JOB_NAME
  displayName: Job Name
  description: Name of the Scheduled Job to Create.
  value: cronjob-prune-images
  required: true
- name: SCHEDULE
  displayName: Cron Schedule
  description: Cron Schedule to Execute the Job
  value: 0 0 * * *
  required: true
- name: JOB_SERVICE_ACCOUNT
  displayName: Service Account Name
  description: Name of the Service Account To Exeucte the Job As.
  value: pruner
  required: true
- name: IMAGE_PRUNE_KEEP_TAG_REVISIONS
  displayName: Number of Tag Revisions
  description: Specify the number of image revisions for a tag in an image stream
    that will be preserved.
  value: '3'
  required: true
- name: IMAGE_PRUNE_KEEP_YOUNGER_THAN
  displayName: Minimum Age of an Image
  description: The minimum age of an image for it to be considered a candidate for
    pruning
  value: 1h0m0s
  required: true
- name: SUCCESS_JOBS_HISTORY_LIMIT
  displayName: Successful Job History Limit
  description: The number of successful jobs that will be retained
  value: '5'
  required: true
- name: FAILED_JOBS_HISTORY_LIMIT
  displayName: Failed Job History Limit
  description: The number of failed jobs that will be retained
  value: '5'
  required: true
- name: "NAMESPACE"
  displayName: "Namespace where this is deployed"
  description: "Namespace where this is deployed."
  value: "cluster-ops"
  required: true
- name: "IMAGE"
  displayName: "Image"
  description: "Image to use for the container."
  required: true
  value: "registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7"
- name: "IMAGE_TAG"
  displayName: "Image Tag"
  description: "Image Tag to use for the container."
  required: true
  value: "v3.11"
- name: STARTING_DEADLINE_SECONDS
  description: Set the startingDeadlineSeconds for the cronjob
  required: false
  value: "60"

labels:
  template: cronjob-prune-images
