apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  schedule: "{{ .Values.cron.schedule }}"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: {{ .Values.cron.historyLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
            env:
            - name: LOG_LEVEL
              value: "{{ .Values.env.logLevel }}"
            - name: DELETE_AFTER_HOURS
              value: "{{ .Values.env.deleteAfterInHours }}"
            - name: DRY_RUN
              value: "{{ .Values.env.dryRun }}"
            - name: GITLAB_API_URL
              value: "{{ .Values.env.gitlabApiUrl }}"
            - name: PARENT_GROUP_ID
              value: "{{ .Values.env.parentGroupId }}"
            - name: NOTIFICATION_URL
              value: "{{ .Values.env.notificationUrl }}"
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: GITLAB_PERSONAL_ACCESS_TOKEN
                  name: {{ .Values.env.secret.name }}
            - name: NOTIFICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  key: NOTIFICATION_TOKEN
                  name: {{ .Values.env.secret.name }}
            imagePullPolicy: Always
            name: {{ .Values.name }}
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          restartPolicy: OnFailure
status: {}
