name: Lint and Test Charts

on: 
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow
      
      - name: Set up Helm
        uses: azure/setup-helm@v2.1
        with:
          version: v3.5.1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v2.2.1
      
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint